context:
  name: libvpl
  version: "2.13.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/intel/libvpl/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 1c740e2b58f7853f56b618bdb7d4a7e5d37f8c1a9b30105a0b79ba80873e1cbd

build:
  skip:
    - win
    - osx
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - make
  host:
    - libva
    - intel-media-driver
  run_exports:
    - ${{ pin_subpackage('libvpl', upper_bound='x.x') }}

tests:
  - script:
    - test -f ${PREFIX}/lib/libvpl.so
    - test -f ${PREFIX}/include/vpl/mfx.h

about:
  homepage: https://github.com/intel/media-driver
  summary: 'Intel® Video Processing Library (Intel® VPL)'
  description: |
    Intel® Video Processing Library (Intel® VPL) provides access to hardware
    accelerated video decode, encode, and processing capabilities on Intel®
    GPUs to support AI visual inference, media delivery, cloud gaming, and
    virtual desktop infrastructure use cases.

  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
